### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by ademilter** [AlbertLucianto/vuex-search#1]
![screen shot 2018-07-02 at 17 44 17](https://user-images.githubusercontent.com/187922/42170578-9ae1f38a-7e1f-11e8-854e-d61918a1f3a8.png)

<img width="617" alt="screen shot 2018-07-02 at 17 43 45" src="https://user-images.githubusercontent.com/187922/42170543-8873d5ce-7e1f-11e8-92b3-6cbe9047d44c.png">

**Comment by AlbertLucianto** [comment]
@ademilter because vuex-search depends on regenerator runtime, you need to either include `transform-runtime` plugin in your babel config,
```json
{
  "plugins": [
    "transform-runtime"
  ]
}
```
or add `babel-polyfill` in your entries (assuming you are using webpack). For example
```js
module.export = {
  entries: [ 'babel-polyfill', './src'],
};
```

Currently, the doc fails to mention this caveat. It should be updated asap.

**Comment by AlbertLucianto** [comment]
Docs updated. Thanks.
